---
title: "数据科学报告"
author: "武碧璇"
date: '2020-03-27'
output:
  html_document:
    df_print: paged
  pdf_document:
    includes:
      in_header: preamble.tex
    number_sections: yes
fontsize: 12pt
documentclass: article
papersize: a5
abstract: |
  思考并完成老师所布置题目，回顾统计知识基础及增强利用R语言处理问题的能力。并且在书写报告的过程中，熟悉RMarkdown的使用方法。
---

# 真值与拟合值比较

使用蒙特卡洛方法对标准正态分布进行拟合。首先，根据标准正态分布的累积密度函数计算各`t`值下的真值。其次，利用标准正态分布的随机样本值，与`t`值进行比较构造计数函数，计算正态分布样本的拟合值。最后，比较不同`t`和`n`值下，蒙特卡洛方法的拟合程度。

```{r, include = FALSE}
tmatrix = t(as.matrix (c(0,0.67,0.84,1.28,1.65,2.32,2.58,3.09,3.72)) )
nmatrix = t(as.matrix (c(100,1000,10000)) )
end = matrix(nrow=3,ncol=9)
```

1. 计算不同`t`值的正态分布真值。
```{r, results='hide', prompt=TRUE, tidy=TRUE}
real = pnorm(tmatrix)
```

2.计算拟合值。将标准正态分布随机样本`X_i`和`t`代入下式求解拟合值。
$$
\begin{aligned}
\hat\Phi(t) = & \frac{1}{n} \sum_{i=1}^n I(X_i \le t)  \\
n \in & \{10^2, 10^3, 10^4\} 
\end{aligned}
$$
使用程序代码如下：
```{r, results='hide', prompt=TRUE, tidy=TRUE}
i = 1
j = 1
while (i<=3){
  n = nmatrix[1,i]

  while (j<=9){
    t = tmatrix[1,j]
    x = as.matrix(rnorm(n))
    y = ifelse((x<=t),1,0)
    end[i,j] = apply(y,2,sum)/n
    j=j+1
  }
  
  j=1
  i=i+1
}
```

3.生成表格，比较真值和拟合值。
```{r, echo=FALSE, prompt=TRUE, tidy=TRUE}
tablevalue = rbind(tmatrix,real,end)
col = as.matrix(c("t","realvalue","n=10^2","n=10^3","n=10^4"))
table = cbind(col,tablevalue)
knitr::kable(table,caption ="Comparison between real values and approximation",format = 'html')

```

# 盒形图
